m = float(input('Digite um valor em metros:'))
#print('O valor {} é {:.0f}cm e {:.0f} mm'.format(m,(m*100),(m*1000)))
print('A medida de {}m corresponde a:'.format(m))
print('{}km'.format(m/1000))
print('{}hm'.format(m/100))
print('{}dam'.format(m/10))
print('{}dm'.format(m*10))
print('{}cm'.format(m*100))
print('{}mm'.format(m*1000))